before_install:
  - gem install bundler

notifications:
  email: false

rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.1
 - 2.1.2
 - ruby-head
 - jruby

gemfile:
  - Gemfile
  - gemfiles/rails-3-2-stable.gemfile
  - gemfiles/rails-4-0-stable.gemfile
  - gemfiles/rails-4-1-stable.gemfile
  - gemfiles/rails-master.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/rails-3-2-stable.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails-3-2-stable.gemfile
    - rvm: ree
      gemfile: gemfiles/rails-3-2-stable.gemfile

before_script:
  - "mysql -e 'create database carrierwave_test;'"
