language: ruby

rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.5
 - ruby-head
 - jruby
 - jruby-head

gemfile:
  - Gemfile
  - gemfiles/rails-3-2-stable.gemfile
  - gemfiles/rails-4-0-stable.gemfile
  - gemfiles/rails-4-1-stable.gemfile
  - gemfiles/rails-master.gemfile

sudo: false

before_script:
  - psql -c 'create database carrierwave_test;' -U postgres

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head # Until JRuby https://github.com/jruby/jruby/issues/1290 is fixed
    - rvm: jruby # Until JRuby https://github.com/jruby/jruby/issues/1290 is fixed

notifications:
  email: false
