dist: trusty

language: ruby

cache: bundler

rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - jruby-9.2.8.0

gemfile:
  - gemfiles/rails-5-2.gemfile
  - gemfiles/rails-6-0.gemfile

before_install:
  # https://github.com/danmayer/coverband/issues/162#issuecomment-452173268
  - rm /home/travis/.rvm/gems/*/specifications/bundler-2.*.gemspec || true
  - gem install bundler -v '<2'

before_script:
  - psql -c 'create database carrierwave_test;' -U postgres

matrix:
  include:
    - rvm: 2.2.10
      gemfile: gemfiles/rails-5-2.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails-5-2.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails-5-2.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/rails-5-0.gemfile
    - rvm: 2.5.7
      gemfile: gemfiles/rails-5-1.gemfile
    - rvm: 2.7.0
      gemfile: gemfiles/rails-master.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails-6-0.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails-5-2.gemfile
  exclude:
    - rvm: jruby-9.2.8.0
      gemfile: gemfiles/rails-6-0.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - gemfile: gemfiles/rails-master.gemfile
  fast_finish: true

notifications:
  email: false
  slack:
    secure: Npzanyv/LXLIRlrNs8iTUbZNRhXlP+K2ZpjZoS2UKkr09jYyP1qdf5a//R3Lu7Yat7g2b4qTJGbaZBEMUQSVaJ6UX6quiBJjVWxjxjQ4Ugk8k/yOIAcGEGYPfS6YzRXemRwo9j4uy76cmwlv8cwEuYTSTBRK4XrdYHslX6pKSXM=

addons:
  postgresql: "9.6"
  apt:
    packages:
      - ghostscript
